output_folder: output_other_variant_callers_pandora_paper_tag1

illumina_tools:
  - snippy
  - samtools

nanopore_tools:
  - medaka
  - nanopolish

coverages:
  - 100

subsampling: random

subsampled_reads_dir: metadata/subsampled_reads_pandora_paper_tag1.csv

references: metadata/references_pandora_paper_tag1.csv

fast5s: metadata/fast5s_pandora_paper_tag1.csv

containers:
  snippy: docker://quay.io/biocontainers/snippy:4.6.0--0
  samtools: docker://leandroishilima/variant_callers_pipeline_samtools:pandora_paper_tag1
  medaka: docker://quay.io/biocontainers/medaka:1.0.3--py36hcc5cce8_0
  nanopolish: docker://leandroishilima/variant_callers_pipeline_nanopolish:pandora_paper_tag1
