output_folder: output_other_variant_callers_small

illumina_tools:
  - snippy
  - samtools

coverages:
  - 10

subsampling: random

samples: metadata/samples_small.csv

references: metadata/references_small.csv

containers:
  snippy: docker://quay.io/biocontainers/snippy:4.6.0--0
  samtools: docker://leandroishilima/variant_callers_pipeline_samtools:pandora_paper_tag1
